version: '3.3'
 
networks:
  common.network:
    driver: bridge
 
volumes:
  mongo.one.vol:
  mongo.two.vol:

services: 
  mongo.one.db:
    container_name: mongo.one.db
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 27017:27017
    volumes:
      - mongo.one.vol:/data/db
      # - ./rs-init.sh:/scripts/rs-init.sh
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=localhost

 
  mongo.two.db:
    container_name: mongo.two.db
    image: mongo:latest
    networks:
      common.network:
    ports:
      - 27018:27018
    depends_on:
      - mongo.one.db
    volumes:
      - mongo.two.vol:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--port", "27018" ]
